### ISSUE TITLE
Peggy 2.0 Documentation for Halborn

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1908]
For Halborn we want two things:
- Documented code
- High level feature documentation

--- 
- Documentation should live in Github and should reference defined terms in other documentation (similar to wikipedia).

Feature Documentation: 
- [ ] Peggy 2.0 PRD ETA 12/17
- [ ] Peggy 2.0 Lock/Burn Arch (Brandon) / EVM to EVM double pegging ETA 12/17
- [ ] Stateless Signature Aggregation (Virtual Mempool) / Denom Hashing - 0.5 weeks ETA 12/17
- [ ] Term Glossary - 0.5 weeks ETA 12/17
- [ ] Transaction Ordering (Sifchain -> Ethereum, Ethereum -> Sifchain) - Fewer dropped txns (Michael) ETA 12/17
- [ ] Removal of Ethereum whitelists (IBC whitelist is not being modified) ETA 12/17
- [ ] Communally Batched transactions 
- [ ] Individually Batched mixed transactions (ETH, erc20) - Not sure if will be functional/needs documentation
- [ ] Relayers, Witness, Smart Contracts, Cosmos Modules - 1 week ETA 12/24

**Comment by pandaring2you** [comment]
Decided at today's sync to parallelize documention with Peggy 2.0 when possible. Unassigned topics (2, 4-7) will be worked on after Integration Tests Pass

**Comment by jzvikart** [comment]
We decided to have documentation in Git instead of Google Docs.
I've started the branch `peggy2-docs` with a proof-of-concept for using docsify.
The documentation is (for now) in `docs/peggy/docs/*.md`.
Instructions are in README.md.

**Comment by pandaring2you** [comment]
https://github.com/Sifchain/sifnode/tree/peggy2-docs/docs/peggy
