### ISSUE TITLE
Add specified peggy2 unit test features (more watchers; see checklist in issue)

### ISSUE THREAD

**Issue by banshee** [Sifchain/sifnode#2094]
- [ ] Add ethereum event watcher
- [x] Add sifnoded log watcher
- [ ] Add process id watcher (to detect death of ebrelayer etc)

**Comment by banshee** [comment]
Checked in.
