### ISSUE TITLE
Playwright v1

### ISSUE THREAD

**Issue by caseyturnerarrington** [Sifchain/sifnode#900]
Epic to track work being done to integrate Cypress Testing.

See Notes:
https://docs.google.com/document/d/1OEY0k7GDJwmEgfGQve4yMohCw9KXo9AmnSQ7yuH7_O8/edit

**Comment by 59023g** [comment]
- [x] Connect Keplr and Metamask Extensions in Potential Test Env
- [x] Decide on Framework: Playwright
- [x] Integrate with Github Action CI ("Headful")
- [x] Write initial test: Import Keplr Account, Connect to Keplr from DEX, Check Balance (From DOM) 
- [ ] Write more Jest + Playwright tests
- [ ] Integrate with Local Test Environment for more Wallet Determinism

https://github.com/Sifchain/sifnode/pull/920 [wip]
